# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile.tests                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: itaharbo <itaharbo@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/11/01 14:07:56 by itaharbo          #+#    #+#              #
#    Updated: 2025/11/13 01:46:24 by itaharbo         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC		= c++
CFLAGS	= -Wall -Wextra -Werror -std=c++98 -I includes

SRCS_SERVER	= srcs/Server/Server.cpp
SRCS_HTTP	= srcs/HttpRequest/HttpRequest.cpp \
			  srcs/HttpRequest/HttpRequest_parsing.cpp \
			  srcs/HttpRequest/HttpRequest_body.cpp \
			  srcs/HttpRequest/HttpRequest_checkers.cpp \
			  srcs/HttpRequest/HttpRequest_getters.cpp
SRCS_RESPONSE = srcs/HttpResponse/HttpResponse.cpp
SRCS_ROUTER = srcs/Router/Router.cpp \
			  srcs/Router/Router_handlers.cpp \
			  srcs/Router/Router_pages.cpp \
			  srcs/Router/Router_pages_2xx.cpp \
			  srcs/Router/Router_pages_3xx.cpp \
			  srcs/Router/Router_pages_4xx.cpp \
			  srcs/Router/Router_pages_5xx.cpp

SRCS_ALL	= $(SRCS_SERVER) $(SRCS_HTTP) $(SRCS_RESPONSE) $(SRCS_ROUTER)

TEST_SERVER			= tests/test_Server.cpp
TEST_HTTP			= tests/test_HttpRequest.cpp
TEST_RESPONSE		= tests/test_HttpResponse.cpp
TEST_ROUTER			= tests/test_Router.cpp
TEST_INTEGRATION	= tests/test_HttpRequest_Server_integration.cpp

TARGET_SERVER		= runTests_Server
TARGET_HTTP			= runTests_HttpRequest
TARGET_RESPONSE		= runTests_HttpResponse
TARGET_ROUTER		= runTests_Router
TARGET_INTEGRATION	= runTests_Integration

all: $(TARGET_SERVER) $(TARGET_HTTP) $(TARGET_RESPONSE) $(TARGET_ROUTER) $(TARGET_INTEGRATION)

# Tests unitaires Server uniquement
$(TARGET_SERVER): $(SRCS_ALL) $(TEST_SERVER)
	$(CC) $(CFLAGS) -o $(TARGET_SERVER) $(SRCS_ALL) $(TEST_SERVER)

# Tests unitaires HttpRequest uniquement
$(TARGET_HTTP): $(SRCS_HTTP) $(TEST_HTTP)
	$(CC) $(CFLAGS) -o $(TARGET_HTTP) $(SRCS_HTTP) $(TEST_HTTP)

# Tests unitaires HttpResponse uniquement
$(TARGET_RESPONSE): $(SRCS_RESPONSE) $(TEST_RESPONSE)
	$(CC) $(CFLAGS) -o $(TARGET_RESPONSE) $(SRCS_RESPONSE) $(TEST_RESPONSE)

# Tests unitaires Router uniquement
$(TARGET_ROUTER): $(SRCS_HTTP) $(SRCS_RESPONSE) $(SRCS_ROUTER) $(TEST_ROUTER)
	$(CC) $(CFLAGS) -o $(TARGET_ROUTER) $(SRCS_HTTP) $(SRCS_RESPONSE) $(SRCS_ROUTER) $(TEST_ROUTER)

# Tests d'intégration Server + HttpRequest + HttpResponse + Router
$(TARGET_INTEGRATION): $(SRCS_ALL) $(TEST_INTEGRATION)
	$(CC) $(CFLAGS) -o $(TARGET_INTEGRATION) $(SRCS_ALL) $(TEST_INTEGRATION)

run_server: $(TARGET_SERVER)
	./$(TARGET_SERVER)

run_http: $(TARGET_HTTP)
	./$(TARGET_HTTP)

run_response: $(TARGET_RESPONSE)
	./$(TARGET_RESPONSE)

run_router: $(TARGET_ROUTER)
	./$(TARGET_ROUTER)

run_integration: $(TARGET_INTEGRATION)
	./$(TARGET_INTEGRATION)

run_all: run_http run_response run_router run_server run_integration

clean:
	rm -f $(TARGET_SERVER) $(TARGET_HTTP) $(TARGET_RESPONSE) $(TARGET_ROUTER) $(TARGET_INTEGRATION)

.PHONY: all run_server run_http run_response run_integration run_all clean
