# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile.tests                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: itaharbo <itaharbo@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/11/01 14:07:56 by itaharbo          #+#    #+#              #
#    Updated: 2025/11/11 23:03:10 by itaharbo         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC		= c++
CFLAGS	= -Wall -Wextra -Werror -std=c++98 -I includes

SRCS_SERVER	= srcs/Server.cpp
SRCS_HTTP	= srcs/HttpRequest.cpp \
			  srcs/HttpRequest_parsing.cpp \
			  srcs/HttpRequest_body.cpp \
			  srcs/HttpRequest_utils.cpp \
			  srcs/HttpRequest_getters.cpp

SRCS_ALL	= $(SRCS_SERVER) $(SRCS_HTTP)

TEST_SERVER			= tests/test_Server.cpp
TEST_HTTP			= tests/test_HttpRequest.cpp
TEST_INTEGRATION	= tests/test_HttpRequest_Server_integration.cpp

TARGET_SERVER		= runTests_Server
TARGET_HTTP			= runTests_HttpRequest
TARGET_INTEGRATION	= runTests_Integration

all: $(TARGET_SERVER) $(TARGET_HTTP) $(TARGET_INTEGRATION)

# Tests unitaires Server uniquement
$(TARGET_SERVER): $(SRCS_ALL) $(TEST_SERVER)
	$(CC) $(CFLAGS) -o $(TARGET_SERVER) $(SRCS_ALL) $(TEST_SERVER)

# Tests unitaires HttpRequest uniquement
$(TARGET_HTTP): $(SRCS_HTTP) $(TEST_HTTP)
	$(CC) $(CFLAGS) -o $(TARGET_HTTP) $(SRCS_HTTP) $(TEST_HTTP)

# Tests d'intégration Server + HttpRequest
$(TARGET_INTEGRATION): $(SRCS_ALL) $(TEST_INTEGRATION)
	$(CC) $(CFLAGS) -o $(TARGET_INTEGRATION) $(SRCS_ALL) $(TEST_INTEGRATION)

run_server: $(TARGET_SERVER)
	./$(TARGET_SERVER)

run_http: $(TARGET_HTTP)
	./$(TARGET_HTTP)

run_integration: $(TARGET_INTEGRATION)
	./$(TARGET_INTEGRATION)

run_all: run_http run_server run_integration

clean:
	rm -f $(TARGET_SERVER) $(TARGET_HTTP) $(TARGET_INTEGRATION)

.PHONY: all run_server run_http run_integration run_all clean
